### ISSUE TITLE
Unable to download the uploaded image

### ISSUE THREAD

**Issue by adi91** [AndyNormore/filemanager#4] opened 2017-05-19 13:25 UTC
Filenotfound exception is coming when I am trying to download the uploaded files.

![image](https://cloud.githubusercontent.com/assets/2649415/26249543/a68889b2-3cc4-11e7-9082-cc0b007f593b.png)

**Comment by skoenfaelt** [comment] 2020-01-27 15:27
Yes I can confirm this behaviour. In my case I could not even show images, but they are found in the filemanager.

**Comment by advancedsoftwarecanada** [comment] 2020-01-27 15:29
Hey wow, can't believe this thing is still being referenced! I can take a look at fixing it up for newer versions of Moodle.

**Comment by advancedsoftwarecanada** [comment] 2020-01-27 15:34
What version of Moodle you guys using?

**Comment by skoenfaelt** [comment] 2020-01-28 06:34
I am using Moodle 3.8
under Moodle 3.7 its partly working. I could download files, but I was not able to show them in an image tag.

Just for my understanding, because the docs are not newbie friendly
Could I upload my file and generate an url to save this url in my database table for this LOCAL plugin?
I know that I only can show the files in the range of my local plugin.

PS: This repo is nicely commented and makes this part of moodle programming easier. It would be cool, if the docs get on this level.

**Comment by anormore** [comment] 2020-01-28 14:09
Ahhh okay, haven't even looked at the newest Moodle. I think this was originally built for 2.4 many years ago. I built this to gain an understanding to how Moodle used files, looks like more stuff changed.... :/

**Comment by skoenfaelt** [comment] 2020-01-29 08:40
I reinstalled your plugin ( since I thought there where some issues with other plugins ) and your plugin works in moodle 3.8 BUT
I used parts of your code in my plugin, just to show some images, and it wont work.
The filearea "attachement" is only for one plugin? so I could not use this for an other plugin?

**Comment by advancedsoftwarecanada** [comment] 2023-11-21 19:45
This should be fixed now, will close. 

@derHodrig yes to answer your question (3 years later) you're kinda stuck with what Moodle gives you. But, you could see how to transport the file to another storage area that is custom so that uploaded files in Moodle could also have a public storage url. 

File management in Moodle is hard.

**Closed as completed by advancedsoftwarecanada** 2023-11-21 19:45 UTC
